title: My Jekyll Site
description: >- # this means to ignore newlines until "baseurl:"
  A simple Jekyll site for GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: modernist
